title: "test"
labels: [Test]
body:
  - type: markdown
    attributes:
      value: |
        test
  - type: textarea
    id: index
    attributes:
      label: test
      description: ""
      value: |
        test
      render: bash
    validations:
      required: true
  - type: textarea
    id: next-task
    attributes:
      label: test
      description: ""
      value: |
        -
      render: bash
    validations:
      required: true