title: "【第X回】2024年XX月XX日"
body:
  - type: textarea
    id: mokuji
    attributes:
      label: 目次
      value: |
        目次はトピックを立てた人が書き加えてください
        - [トピックタイトル](URL)
        - 結論
    validations:
      required: true
  - type: textarea
    id: nexttask
    attributes:
      label: 次の一週間でやること
      value: |
        - やること
    validations:
      required: true
  - type: textarea
    id: format
    attributes:
      label: トピック用フォーマット
      value: |
        ## 概要

        ## 結論

        ## 関連Issues, Discussions
        <!-- あれば書いてください -->
    validations:
      required: true
